name: Build and Deploy Spring Boot Application

# Trigger the workflow on push to main branch
on:
  push:
    branches:
      - main

# Jobs to build and deploy the application
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"
          cache: "maven"

      - name: Run tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ secrets.USER_DOCKERHUB }}/spring-boot-ci-cd:latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_DOCKERHUB }}
          password: ${{ secrets.ACCESS_TOKEN_DOCKERHUB }}

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.USER_DOCKERHUB }}/spring-boot-ci-cd:latest
