name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Unit test the application
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ secrets.USER_DOCKERHUB }}/spring-boot-CI-CD:latest

      - name: Login to DockerHub
        run: echo "${{ secrets.ACCESS_TOKEN_DOCKERHUB }}" | docker login -u ${{ secrets.USER_DOCKERHUB }} --password-stdin # Login to DockerHub

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.USER_DOCKERHUB }}/spring-boot-ci-cd:latest
