name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Unit test the application
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: mvn -B package --file pom.xml
